name: plant-leaf-disease-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - opencv=4.5.3
  - tensorflow=2.6
  - jupyterlab
  - matplotlib
  - seaborn
  - pip
  - pip:
      - albumentations   # For data augmentation
